branch-defaults:
  master:
    environment: clouddevopsec-environment
    group_suffix: null
environment-defaults:
  clouddevops-environment:
    branch: null
    repository: null
global:
  application_name: clouddevops-web-proj
  branch: null
  default_ec2_keyname: aws-eb4
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
